POST http://localhost:3001/api/coins/ HTTP/1.1

Content-Type: application/json
{
    "id": "bitcoin",
    "name": "Bitcoin",
    "current_price": "34570",
    "market_cap": "648054345980",
    "market_cap_rank": "1",
    "price_change_percentage_24h": "2.56644"
}